# Generated by Django 3.2.7 on 2021-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202008',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202008',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202009',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202009',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202010',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202011',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202011',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202012',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202012',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202101',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202102',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202102',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202103',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202103',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202104',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202104',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202105',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202105',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202106',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202106',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202107',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202107',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfFreq202108',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'df_freq_202108',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202008',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202008',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202009',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202009',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202010',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202011',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202011',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202012',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202012',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202101',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202102',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202102',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202103',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202103',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202104',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202104',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202105',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202105',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202106',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202106',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202107',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202107',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfFreq202108',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('num', models.TextField()),
            ],
            options={
                'db_table': 'tf_freq_202108',
                'managed': False,
            },
        ),
    ]
